<?php
/**
 * OD-base.
 *
 * WARNING: This file is part of the OD-base theme. DO NOT edit this file
 * under any circumstances, as the changes will be lost in the case of a theme update.
 * Please do all modifications in the form of a child theme.
 *
 * @since   1.0.0
 * @package OD-base\Templates\Partials
 * @author  OlivasDigital
 * @license GPL-2.0+
 * @link    https://olivas.digital/
 */

namespace OD\Theme\Templates\Partials;

/**
 * Pagination.
 *
 * @since  1.0.0
 * @author OlivasDigital
 */
class Pagination {


	/**
	 * Render pagination.
	 *
	 * @since 1.0.0
	 */

	public static function render() {       ?>
		<div class="pagination-container">
			<?php
			the_posts_pagination(
				array(
					'mid_size'           => 1,
					'screen_reader_text' => ' ',
					'prev_text'          => __( 'Prev', 'olivasdigital' ),
					'next_text'          => __( 'Next', 'olivasdigital' ),
					'show_all'           => false,
				)
			);
			?>
		</div>
		<?php
	}
}
