version: '3.7'

services:

  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wp_project/:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_ADDITIONAL_PERMISSION_CONFIG: define( 'FS_METHOD','direct' );
      WORDPRESS_ADDITIONAL_CONFIG: define( 'WPCF7_AUTOP', false );

volumes:
    db_data:
    php_data: