<?php
/**
 * OD Images.
 *
 * Use this class to add image related functionality. If not needed please remove, don't forget to update
 * functions.php accordingly
 *
 * WARNING: This file is part of the OD Base theme. DO NOT edit this file
 * under any circumstances, as the changes will be lost in the case of a theme update.
 * Please do all modifications in the form of a child theme.
 *
 * @since   1.0.0
 * @package OD\Theme\Base
 * @author  OlivasDigital
 * @license GPL-2.0+
 * @link    https://olivas.digital/
 */

namespace OD\Theme;

/**
 * Image related actions.
 *
 * @since  1.0.0
 * @author OlivasDigital
 */
class Images {


	/**
	 * Adds image sizes.
	 *
	 * @since 1.0.0
	 */
	public function ready() {
		add_image_size( 'sm-thumbnails', 774, 325, false );
		add_image_size( 'xs-thumbnails', 774, 598, false );
		add_image_size( 'md-thumbnails', 865, 902, false );
		add_image_size( 'xm-thumbnails', 940, 914, false );
		add_image_size( 'lg-thumbnails', 994, 693, false );
		add_image_size( 'xl-thumbnails', 1305, 455, false );
		add_image_size( 'desk-thumbnails', 1305, 693, false );
		add_image_size( 'full-thumbnails', 1920, 1080, false );
	}
}
