<?php
/**
 * OD-base.
 *
 * WARNING: This file is part of the OD-base theme. DO NOT edit this file
 * under any circumstances, as the changes will be lost in the case of a theme update.
 * Please do all modifications in the form of a child theme.
 *
 * @since   1.0.0
 * @package OD
 * @author  OlivasDigital
 * @license GPL-2.0+
 * @link    https://olivas.digital/
 */

namespace OD\Theme;

/**
 * Theme options.
 *
 * @since  1.0.0
 */
class Options {


	/**
	 * Get theme option.
	 *
	 * @since  1.0.0
	 * @param  string $key     Name of option to retrieve.
	 * @param  mixed  $default Optional. Default value to return if the option does not exist.
	 * @return string          Value set for the option.
	 */
	public static function get_option( $key, $default = false ) {

		if ( empty( $key ) ) {
			return '';
		}

		return get_option( "od_{$key}", $default );
	}

	public function ready() {
		if ( function_exists( 'acf_add_options_page' ) ) {
			acf_add_options_page(
				array(
					'page_title'  => '404',
					'menu_title'  => '404',
					'menu_slug'   => 'four-hundred-and-four-config',
					'capability'  => 'edit_posts',
					'parent_slug' => '',
					'position'    => 18,
					'icon_url'    => 'dashicons-no',
					'redirect'    => false,
				)
			);

			acf_add_options_page(
				array(
					'page_title'  => 'Header',
					'menu_title'  => 'Header',
					'menu_slug'   => 'header-config',
					'capability'  => 'edit_posts',
					'parent_slug' => '',
					'position'    => 19,
					'icon_url'    => 'dashicons-admin-page',
					'redirect'    => false,
				)
			);

			acf_add_options_page(
				array(
					'page_title'  => 'Footer',
					'menu_title'  => 'Footer',
					'menu_slug'   => 'footer-config',
					'capability'  => 'edit_posts',
					'parent_slug' => '',
					'position'    => 21,
					'icon_url'    => 'dashicons-admin-page',
					'redirect'    => false,
				)
			);
		}
	}
}
