<?php
/**
 * OD Scripts.
 *
 * WARNING: This file is part of the OD Base theme. DO NOT edit this file
 * under any circumstances, as the changes will be lost in the case of a theme update.
 * Please do all modifications in the form of a child theme.
 *
 * @since   1.0.0
 * @package OD\Theme\Base
 * @author  OlivasDigital
 * @license GPL-2.0+
 * @link   https://olivas.digital/
 */

namespace OD\Theme;

/**
 * Theme scripts.
 *
 * @since  1.0.0
 * @author OlivasDigital
 */
class Scripts {


	/**
	 * Base URL for public assets.
	 *
	 * @since 1.0.0
	 * @var   string
	 */
	private $base_uri;
	private $base_dir;

	/**
	 * Assets suffix.
	 *
	 * @since 1.0.0
	 * @var   string
	 */
	private $suffix;

	/**
	 * Constructor.
	 *
	 * @since 1.0.0
	 */
	public function __construct() {
		$this->base_uri = get_stylesheet_directory_uri() . '/dist/';
		$this->base_dir = get_stylesheet_directory() . '/dist/';
		$this->suffix   = od_is_dev() ? '' : '.min';
	}

	/**
	 * Setup hooks.
	 *
	 * @since 1.0.0
	 */
	public function ready() {
		add_action( 'wp_enqueue_scripts', array( $this, 'enqueue' ) );
	}

	/**
	 * Enqueue scripts.
	 *
	 * Fired on `wp_enqueue_scripts`.
	 *
	 * @since 1.0.0
	 */
	public function enqueue() {
		wp_enqueue_script(
			'OD',
			$this->base_uri . "main{$this->suffix}.js",
			array( 'jquery-core' ),
			filemtime( $this->base_dir . "main{$this->suffix}.js" ),
			true,
		);

		wp_localize_script(
			'OD',
			'WP_AJAX',
			array(
				'ajaxurl' => admin_url( 'admin-ajax.php' ),
				'WP_ENV'  => WP_ENV,
			)
		);
	}
}
