<?php
/**
 * OD Content.
 * This class is used to add content relevant methods
 *
 * WARNING: This file is part of the OD Base theme. DO NOT edit this file
 * under any circumstances, as the changes will be lost in the case of a theme update.
 * Please do all modifications in the form of a child theme.
 *
 * @since   1.0.0
 * @package OD\Theme\Structure
 * @author  OlivasDigital
 * @license GPL-2.0+
 * @link    https://olivas.digital/
 */

namespace OD\Theme\Structure;

/**
 * Content rendering functions for the templates.
 *
 * @since  1.0.0
 * @author OlivasDigital
 */
class Content {


	/**
	 * Setup hooks.
	 *
	 * @since 1.0.0
	 */
	public function ready() {
		add_filter( 'excerpt_more', array( $this, 'excerpt_more' ) );
	}

	/**
	 * Move the comment field to bottom in the comments form.
	 *
	 * @since 1.0.0
	 * @param string $more The string shown within the more link.
	 */
	public function excerpt_more( $more ) {
		return sprintf(
			' <a class="read-more" href="%s" title="%s">%s</a>',
			esc_url( get_the_permalink() ),
			esc_attr__( 'Learn More', 'olivasdigital' ),
			__( 'Learn More', 'olivasdigital' )
		);
	}
}
