<?php
/**
 * OD Navigation
 *
 * WARNING: This file is part of the OD Base theme. DO NOT edit this file
 * under any circumstances, as the changes will be lost in the case of a theme update.
 * Please do all modifications in the form of a child theme.
 *
 * @since   1.0.0
 * @package OD\Theme\Structure
 * @author  OlivasDigital
 * @license GPL-2.0+
 * @link    https://olivas.digital/
 */

namespace OD\Theme\Structure;

/**
 * Register custom navigation menus.
 *
 * @since  1.0.0
 * @author OlivasDigital
 */
class Navigation {


	/**
	 * Setup hooks.
	 *
	 * @since 1.0.0
	 */
	public function ready() {
		register_nav_menus(
			array(
				'primary'   => esc_html__( 'Main Menu', 'olivasdigital' ),
				'footer'    => esc_html__( 'Footer Menu', 'olivasdigital' ),
				'site-info' => esc_html__( 'Site Info Menu', 'olivasdigital' ),
			)
		);
	}
}
